MINIMA=$(dirname $(readlink ${BASH_SOURCE[0]}))
. $MINIMA/../ponyrc/colors.bash
. $MINIMA/../ponyrc/discord.bash

PS1="$PONY_PS1_START$PONY_RANDOM\t$PONY_DIRECTORY \W$PONY_RESET$PONY_PS1_END "
PATH=$PATH:node_modules/.bin
TERM=xterm-256color

export EDITOR='vim'
export CLICOLOR=1

# Color ls for Linux.
if [ $(uname) == "Linux"  ]; then
  alias ls="ls --color=auto"
fi

alias l="ls -la"
alias less="less -r"

# Avoid python3 for npm on Arch.
if [ -f /usr/bin/python2.7 ]; then
  alias npm="PYTHON=python2.7 npm"
fi
alias screen="screen -U"
