" Enable default settings.
set textwidth=80
set wildmenu
syntax enable
filetype plugin indent on

" Add non-standard extensions.
autocmd BufRead,BufNewFile *.md set filetype=markdown

" Add filetype local behavior. 
autocmd FileType gitcommit,markdown setlocal spell
autocmd FileType css setlocal iskeyword+=-

" Auto indent with size 2 tabs.
set smartindent
set shiftwidth=2
set tabstop=2
set expandtab

" Map jk to allow moving by visual line.
map j gj
map k gk

" Map ^hjkl to window panes.
map <silent> <C-h> <C-w>h
map <silent> <C-j> <C-w>j
map <silent> <C-k> <C-w>k
map <silent> <C-l> <C-w>l

" Map ^e to close pane if there are no changes.
map <silent> <C-e> :q<cr>

" Map -= to horizontal, <> to vertical pane resize.
map - <C-w>-
map = <C-w>+
map < <C-w><
map > <C-w>>

" Allow <> to change indentation is visual mode.
vmap > >gv
vmap < <gv

" Reload the current buffer if changed externally.
au BufEnter * checktime
set autoread
